services:
  web:
    image: nginx:alpine
    restart: always
    expose:
      - "80"
    networks:
      easypanel_net:
        aliases:
          - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=easypanel"
      - "traefik.http.routers.webcole-web.rule=Host(`webcole-web.kmluyu.easypanel.host`)"
      - "traefik.http.routers.webcole-web.entrypoints=websecure"
      - "traefik.http.routers.webcole-web.tls=true"
      - "traefik.http.services.webcole-web.loadbalancer.server.port=80"

networks:
  easypanel_net:
    name: easypanel
    external: true
